### PR TITLE
US2057: Adding pg8000 required by sqlalchemy for connecting to post…

### PR DESCRIPTION
**Pull request by bethrichardson**
…gres database

### CODE REVIEW

**Comment by arcivanov** [comment]
@bethrichardson really quickly: psycopg2 is a hybrid driver and requires native components installed. Can we try with a fully Python implementation for now?

**Comment by arcivanov** [comment]
add to whitelist

**Comment by bethrichardson** [comment]
@arcivanov This should be ready for you to review. Thanks!

**Comment by arcivanov** [comment]
This shall be merged!

**Pull request merged**
