### PR TITLE
TA2538 expanding logging support

### PR DESCRIPTION
**Pull request by jrombs**

### CODE REVIEW

**Comment by jrombs** [comment]
@arcivanov this supports the pull request on cschcs-manager for TA2538. It is ready for review.

**Comment by arcivanov** [comment]
@jrombs The config is here pending the next stop of not using templates? Just want to confirm this one

**Comment by arcivanov** [comment]
This shall be merged!

**Comment by arcivanov** [comment]
@jrombs once this is merged, please remove `.pyenv` from cschcs/cschcs-manager#21

**Pull request merged**
