### PR TITLE
US2110 PyEnv needs requirements split

### PR DESCRIPTION
**Pull request by arcivanov**

### CODE REVIEW

**Comment by arcivanov** [comment]
@jrombs @bethrichardson please review

**Comment by jrombs** [comment]
This shall be merged!

**Comment by jrombs** [comment]
This shall be merged!

**Comment by arcivanov** [comment]
retest this please

**Comment by arcivanov** [comment]
retest this please

**Comment by arcivanov** [comment]
This shall be merged!

**Comment by jrombs** [comment]
This shall be merged!

**Comment by jrombs** [comment]
This shall be merged!

**Comment by jrombs** [comment]
This shall be merged!

**Comment by jrombs** [comment]
This shall be merged!

**Comment by jrombs** [comment]
This shall be merged!

**Comment by jrombs** [comment]
This shall be merged!

**Comment by jrombs** [comment]
This shall be merged!

**Comment by jrombs** [comment]
This shall be merged!

**Comment by arcivanov** [comment]
This shall be merged!

**Comment by ocheret** [comment]
This shall be merged!

**Comment by ocheret** [comment]
This shall be merged!

**Comment by ocheret** [comment]
This shall be merged!

**Comment by ocheret** [comment]
This shall be merged!

**Comment by ocheret** [comment]
This shall be merged!

**Comment by ocheret** [comment]
This shall be merged!

**Comment by ocheret** [comment]
This shall be merged!

**Comment by ocheret** [comment]
This shall be merged!

**Comment by ocheret** [comment]
This shall be merged!

**Comment by ocheret** [comment]
This shall be merged!

**Comment by ocheret** [comment]
This shall be merged!

**Comment by ocheret** [comment]
This shall be merged!

**Comment by arcivanov** [comment]
test this please

**Comment by ocheret** [comment]
This shall be merged!

**Comment by arcivanov** [comment]
test this please

**Comment by arcivanov** [comment]
test this please

**Comment by arcivanov** [comment]
test this please

**Comment by ocheret** [comment]
This shall be merged!

**Pull request merged**
